---
title: rua com vida
description: Democratização do espaço urbano
lang: pt
logo: /assets/img/logo.png
author:
  name: Afonso Cerejeira
navbar:
  - name: Início
    url: /
  - name: Arquivo
    url: /arquivo
  - name: Sobre
    url: /sobre
  - name: Contacto
    url: /contacto
---
